<a href="https://colab.research.google.com/github/kenltho2/Num-Meth23/blob/main/Project4ver3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project 4 ver2
Aaron Arias Vales, Kennedy Thomas
We begin our project for creating functions for the elementary row operations on matrices. The swap(a,b) function swaps rows 
 and 
 of our matrix 
. The k(a,k) function returns 
 for row 
 in 
. Lastly, the multiple(k,row_to_multiply,new_row) function returns 
 for 
 in 
 where a = row_to_multiply and b = new_row.

In [33]:
import numpy as np
#solving systems of equations

#function to create an augmented matrix
#n = number of unknowns
#np.zeros((3,4)) creates a 3 x 4 array of 0s to start out
A = np.zeros((3,4))

def create_augmented_matrix():
    n = len(A)
    #loop to input individual values for each unknown coefficient, returning the complete initial augmented matrix
    #row count
    for i in range (n):
        
        #column count, 1 extra because this is an augmented matrix; col4 = result
        for j in range(n+1):
            A[i][j] = float(input('A['+str(i+1)+']['+str(j+1)+'] = '))

We then test our EROs with a sample system of equations. I have chosen a homogenous system to perform Gauss-Jordan elimination upon, and will reduce the matrix to Reduced Row Echelon Form. The equations in our system are:

 

We can describe this system with matrices as follows:

 
 
 

For Gauss-Jordan elimination, we need to convert these matrices to one augmented matrix. We convert to the augmented matrix below and begin to solve our equation with our ERO functions.

 


In [34]:
create_augmented_matrix()

A[1][1] = 2
A[1][2] = -1
A[1][3] = -3
A[1][4] = 0
A[2][1] = -1
A[2][2] = 2
A[2][3] = -3
A[2][4] = 0
A[3][1] = 1
A[3][2] = 1
A[3][3] = 4
A[3][4] = 0


In [35]:
#function for swapping rows
def swap(a,b):
    A[[a-1,b-1]] = A[[b-1,a-1]]
    return A

In [36]:
#function for multiplying by a constant
def k(a,k):
    A[a-1] = k*A[a-1]
    return A

In [37]:
#function for adding multiple of other row
def multiple(k,row_to_multiply,new_row):
    a = row_to_multiply
    b = new_row
    A[b-1] = k*A[a-1] + A[b-1] 
    return A

In [38]:
A

array([[ 2., -1., -3.,  0.],
       [-1.,  2., -3.,  0.],
       [ 1.,  1.,  4.,  0.]])

In [39]:
swap(1,3)

array([[ 1.,  1.,  4.,  0.],
       [-1.,  2., -3.,  0.],
       [ 2., -1., -3.,  0.]])

In [40]:
multiple(1,1,2)

array([[ 1.,  1.,  4.,  0.],
       [ 0.,  3.,  1.,  0.],
       [ 2., -1., -3.,  0.]])

In [41]:
multiple(-2,1,3)

array([[  1.,   1.,   4.,   0.],
       [  0.,   3.,   1.,   0.],
       [  0.,  -3., -11.,   0.]])

In [42]:
multiple(1,2,3)

array([[  1.,   1.,   4.,   0.],
       [  0.,   3.,   1.,   0.],
       [  0.,   0., -10.,   0.]])

In [43]:
k(2,1/3)

array([[  1.        ,   1.        ,   4.        ,   0.        ],
       [  0.        ,   1.        ,   0.33333333,   0.        ],
       [  0.        ,   0.        , -10.        ,   0.        ]])

In [44]:
k(3,-1/10)

array([[ 1.        ,  1.        ,  4.        ,  0.        ],
       [ 0.        ,  1.        ,  0.33333333,  0.        ],
       [-0.        , -0.        ,  1.        , -0.        ]])

In [45]:
multiple(-1/3,3,2)

array([[ 1.,  1.,  4.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

In [46]:
multiple(-4,3,1)

array([[ 1.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

In [47]:
multiple(-1,2,1)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

 Here is an algorithm for solving systems of equations using the Gauss-Jordan elimination method

In [50]:
# INPUT: augmented matrix A representing a system of equations
# OUTPUT: the reduced row echelon form of A

for i in range(len(A)):
    # Divide row i by the pivot element A[i][i]:
    multiply_row(A, i, 1/A[i][i])
    
    # Eliminate all entries below the pivot element:
    for j in range(i+1, len(A)):
        add_rows(A, j, i, -A[j][i])
    
    # Eliminate all entries above the pivot element:
    for j in range(i):
        add_rows(A, j, i, -A[j][i])
        
    # If the pivot element is 0, swap with a row below that has a non-zero entry in that column:
    if A[i][i] == 0:
        for j in range(i+1, len(A)):
            if A[j][i] != 0:
                swap_rows(A, i, j)
                break

print(A)


[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1. -0.]]


##2 The Explanations
##a)
 The Gauss-Jordan elimination method is a powerful technique for solving systems of equations. It works by transforming the augmented matrix representing the system into its reduced row echelon form, which makes it easy to read off the solutions. In this report, we defined functions for swapping rows, adding rows, and multiplying by a constant, and used these functions to perform the Gauss-Jordan process on a system of equations. We also created an algorithm that can be used to solve systems of equations using the Gauss-Jordan method.

##b)
The Gauss-Jordan elimination method can be computationallyh expensive for very large system of equations. The fault lies when a when a matrix contains a row of zeros. One way to fix this is when you locate a row of zeros is to swap them with non-zero rows below them. In closing the Gauss-Jordan elimination method is a poweerful technique for solving systems of equations it does have limitations that should be taken into account, and additional steps may be needed to ensure it's applicability. 