In [131]:
import numpy as np
#solving systems of equations

#function to create an augmented matrix
#n = number of unknowns
#np.zeros((3,4)) creates a 3 x 4 array of 0s to start out
A = np.zeros((3,4))

def create_augmented_matrix():
    n = len(A)
    #loop to input individual values for each unknown coefficient, returning the complete initial augmented matrix
    #row count
    for i in range (n):
        
        #column count, 1 extra because this is an augmented matrix; col4 = result
        for j in range(n+1):
            A[i][j] = float(input('A['+str(i+1)+']['+str(j+1)+'] = '))

In [141]:
create_augmented_matrix()

A[1][1] = 2
A[1][2] = -1
A[1][3] = -3
A[1][4] = 0
A[2][1] = -1
A[2][2] = 2
A[2][3] = -3
A[2][4] = 0
A[3][1] = 1
A[3][2] = 1
A[3][3] = 4
A[3][4] = 0


In [100]:
#function for swapping rows
def swap(a,b):
    A[[a-1,b-1]] = A[[b-1,a-1]]
    return A

In [108]:
#function for multiplying by a constant
def k(a,k):
    A[a-1] = k*A[a-1]
    return A

In [138]:
#function for adding multiple of other row
def multiple(k,row_to_multiply,new_row):
    a = row_to_multiply
    b = new_row
    A[b-1] = k*A[a-1] + A[b-1] 
    return A

In [142]:
A

array([[ 2., -1., -3.,  0.],
       [-1.,  2., -3.,  0.],
       [ 1.,  1.,  4.,  0.]])

**$R_{1} \leftrightarrow R_{3}$**

In [143]:
swap(1,3)

array([[ 1.,  1.,  4.,  0.],
       [-1.,  2., -3.,  0.],
       [ 2., -1., -3.,  0.]])

**$R_{2} + R_{1}$**

In [144]:
multiple(1,1,2)

array([[ 1.,  1.,  4.,  0.],
       [ 0.,  3.,  1.,  0.],
       [ 2., -1., -3.,  0.]])

**$-2R_{1} + R_{3}$**

In [145]:
multiple(-2,1,3)

array([[  1.,   1.,   4.,   0.],
       [  0.,   3.,   1.,   0.],
       [  0.,  -3., -11.,   0.]])

**$R_{2} + R_{3}$**

In [146]:
multiple(1,2,3)

array([[  1.,   1.,   4.,   0.],
       [  0.,   3.,   1.,   0.],
       [  0.,   0., -10.,   0.]])

In [147]:
k(2,1/3)

array([[  1.        ,   1.        ,   4.        ,   0.        ],
       [  0.        ,   1.        ,   0.33333333,   0.        ],
       [  0.        ,   0.        , -10.        ,   0.        ]])

In [151]:
k(3,-1)

array([[ 1.        ,  1.        ,  4.        ,  0.        ],
       [ 0.        ,  1.        ,  0.33333333,  0.        ],
       [-0.        , -0.        ,  1.        , -0.        ]])

In [153]:
multiple(-2/3,3,2)

array([[ 1.,  1.,  4.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

In [154]:
multiple(-4,3,1)

array([[ 1.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

In [155]:
multiple(-1,2,1)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

**This homogenous linear system is accurate for all $x,y,z \in \mathbb{R}.$**