#### <div align="right"> April 9 2023 -- CPSMA 4413 -- Dr. Jacob </div>

# Project 4 

## Aaron Arias Vales, Kennedy Thomas

**We begin our project for creating functions for the elementary row operations on matrices. The `swap(a,b)` function swaps rows $R_{a}$ and $R_{b}$ of our matrix $A$. The `k(a,k)` function returns $kR_{a}$ for row $R_{a}$ in $A$. Lastly, the `multiple(k,row_to_multiply,new_row)` function returns $kR_{a} + R_{b}$ for $R_{b}$ in $A$ where `a = row_to_multiply` and `b = new_row`.**

In [2]:
import numpy as np
#solving systems of equations

#function to create an augmented matrix
#n = number of unknowns
#np.zeros((3,4)) creates a 3 x 4 array of 0s to start out
A = np.zeros((3,4))

def create_augmented_matrix(matrix_skeleton):
    n = len(matrix_skeleton)
    #loop to input individual values for each unknown coefficient, returning the complete initial augmented matrix
    #row count
    for i in range (n):
        
        #column count, 1 extra because this is an augmented matrix; col4 = result
        for j in range(n+1):
            matrix_skeleton[i][j] = float(input(str(matrix_skeleton)+'['+str(i+1)+']['+str(j+1)+'] = '))

**We then test our EROs with a sample system of equations. I have chosen a homogenous system to perform Gauss-Jordan elimination upon, and will reduce the matrix to Reduced Row Echelon Form. The equations in our system are:**

**$\begin{cases} 2x-y-3z=0 \\
               -x+2y-3z=0 \\
               x+y+4z=0 \end{cases}$**

**We can describe this system with matrices as follows:**

$\begin{bmatrix} 2 & -1 & -3 \\
                -1 &  2 & -3 \\
                1  &  1 &  4 \end{bmatrix}
 \begin{bmatrix} x \\
                 y \\
                 z \end{bmatrix} = \begin{bmatrix} 0 \\
                                                   0 \\
                                                   0 \end{bmatrix}$

**For Gauss-Jordan elimination, we need to convert these matrices to one augmented matrix. We convert to the augmented matrix below and begin to solve our equation with our ERO functions.**

$\left[\begin{array}{ccc|c}
2 & -1 & -3 & 0 \\
-1 & 2 & -3 & 0 \\
1  & 1  &  4 & 0 \end{array}\right]
$

In [141]:
create_augmented_matrix()

A[1][1] = 2
A[1][2] = -1
A[1][3] = -3
A[1][4] = 0
A[2][1] = -1
A[2][2] = 2
A[2][3] = -3
A[2][4] = 0
A[3][1] = 1
A[3][2] = 1
A[3][3] = 4
A[3][4] = 0


In [3]:
#function for swapping rows
def swap(matrix,a,b):
    matrix[[a-1,b-1]] = matrix[[b-1,a-1]]
    return matrix

In [4]:
#function for multiplying by a constant
def k(matrix,a,k):
    matrix[a-1] = k*matrix[a-1]
    return matrix

In [5]:
#function for adding multiple of other row
def multiple(matrix,k,row_to_multiply,new_row):
    a = row_to_multiply
    b = new_row
    matrix[b-1] = k*matrix[a-1] + matrix[b-1] 
    return matrix

In [142]:
A

array([[ 2., -1., -3.,  0.],
       [-1.,  2., -3.,  0.],
       [ 1.,  1.,  4.,  0.]])

**$R_{1} \leftrightarrow R_{3}$**

In [143]:
swap(1,3)

array([[ 1.,  1.,  4.,  0.],
       [-1.,  2., -3.,  0.],
       [ 2., -1., -3.,  0.]])

**$R_{2} + R_{1}$**

In [144]:
multiple(1,1,2)

array([[ 1.,  1.,  4.,  0.],
       [ 0.,  3.,  1.,  0.],
       [ 2., -1., -3.,  0.]])

**$-2R_{1} + R_{3}$**

In [145]:
multiple(-2,1,3)

array([[  1.,   1.,   4.,   0.],
       [  0.,   3.,   1.,   0.],
       [  0.,  -3., -11.,   0.]])

**$R_{2} + R_{3}$**

In [146]:
multiple(1,2,3)

array([[  1.,   1.,   4.,   0.],
       [  0.,   3.,   1.,   0.],
       [  0.,   0., -10.,   0.]])

**$\frac{1}{3}R_{2}$**

In [147]:
k(2,1/3)

array([[  1.        ,   1.        ,   4.        ,   0.        ],
       [  0.        ,   1.        ,   0.33333333,   0.        ],
       [  0.        ,   0.        , -10.        ,   0.        ]])

**$-\frac{1}{10}R_{3}$**

In [151]:
k(3,-1/10)

array([[ 1.        ,  1.        ,  4.        ,  0.        ],
       [ 0.        ,  1.        ,  0.33333333,  0.        ],
       [-0.        , -0.        ,  1.        , -0.        ]])

**$R_{2}-\frac{1}{3}R_{3}$**

In [153]:
multiple(-1/3,3,2)

array([[ 1.,  1.,  4.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

**$R_{1}-4R_{3}$**

In [154]:
multiple(-4,3,1)

array([[ 1.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

**$R_{1}-R_{2}$**

In [155]:
multiple(-1,2,1)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

**We have reduced our matrix to RREF.**

**The only solution for this homogenous system is the trivial solution, where $
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = \begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}$**

In [ ]:
import numpy as np

# Define the Gauss-Jordan elimination function
def gauss_jordan_elimination(A):
    n = A.shape[0]
    for i in range(n):
        # Find the row with the maximum absolute value in the current column
        max_row = i
        for j in range(i+1, n):
            if abs(A[j,i]) > abs(A[max_row,i]):
                max_row = j
        
        # Swap the current row with the row with maximum absolute value
        A[[i,max_row]] = A[[max_row,i]]
        
        # Normalize the current row
        A[i] = A[i] / A[i,i]
        
        # Eliminate the current column in the other rows
        for j in range(n):
            if j != i:
                A[j] = A[j] - A[j,i] * A[i]
    
    # Extract the solution
    solution = A[:,n]
    
    return solution

# Define the matrix A
A = np.array([[2, -1, -3, 0], [-1, 2, -3, 0], [1, 1, 4, 0]])

# Apply the operations to the matrix A
operations = [("swap", 1, 3), ("multiple", -2, 1, 3), ("multiple", 1, 2, 3), 
              ("k", 2, 1//3), ("k", 3, -1//10), ("multiple", -1/3, 3, 2), 
              ("multiple", -4, 3, 1), ("multiple", -1, 2, 1)]
for op, *args in operations:
    if op == "swap":
        i, j = args
        A[[i-1, j-1]] = A[[j-1, i-1]]
    elif op == "multiple":
        k, i, j = args
        A[i-1] = k * A[j-1] + A[i-1]
    elif op == "k":
        k, i = args
        A[i-1] = k * A[i-1]

# Print the result
print(A)

# Solve the system of equations using Gauss-Jordan elimination
solution = gauss_jordan_elimination(np.hstack((A, np.array([[4], [0], [0]]))))
print(solution)

##2 The Explanations
##a)
 The Gauss-Jordan elimination method is a powerful technique for solving systems of equations. It works by transforming the augmented matrix representing the system into its reduced row echelon form, which makes it easy to read off the solutions. In this report, we defined functions for swapping rows, adding rows, and multiplying by a constant, and used these functions to perform the Gauss-Jordan process on a system of equations. We also created an algorithm that can be used to solve systems of equations using the Gauss-Jordan method.

##b)
The Gauss-Jordan elimination method can be computationallyh expensive for very large system of equations. The fault lies when a when a matrix contains a row of zeros. One way to fix this is when you locate a row of zeros is to swap them with non-zero rows below them. In closing the Gauss-Jordan elimination method is a poweerful technique for solving systems of equations it does have limitations that should be taken into account, and additional steps may be needed to ensure it's applicability. 